language: minimal
sudo: required

services:
  - docker

before_install:
  - chmod +x build.sh
  - chmod +x dist.sh
branches:
  only:
  - dev

jobs:
  include:
    - stage: Build Docker Images
      script:
        - $TRAVIS_BUILD_DIR/build.sh
    - stage: Deploy Docker Images to Docker Hub
      script:
        - $TRAVIS_BUILD_DIR/dist.sh

