language: minimal
sudo: required

services:
  - docker

branches:
  only:
  - dev

before_install:
  - chmod +x build.sh
  - chmod +x dist.sh


jobs:
  include:
    - stage: Build Docker Images
      script:
        - $TRAVIS_BUILD_DIR/build.sh
    - stage: Deploy Docker Images to Docker Hub
      script:
        - $TRAVIS_BUILD_DIR/dist.sh

